import type { Capability, Role } from './authTypes'

/**
 * Capability sets per role, derived from the S&D/CRM deck's own org chart and
 * the lifting chain on slides 6 and 7. This file is the org model in code: the
 * demand, the recommendation, the approval, the ERP invoice and the revenue
 * assurance are five different people, and each only sees their own step.
 *
 * The real service owns this mapping. It lives here so the mock can exercise
 * every role, and so the intended split is reviewable before the API is built.
 */

const RETAILER: Capability[] = [
  'sim.activate',
  'sim.replace',
  'sim.choiceNumber',
  'sim.ownership',
  'sim.planMigration',
  'customer.search',
  'mnp.portIn',
  'mnp.portOut',
  'mnp.status',
  'recharge.sell',
  'recharge.flexiload',
  'recharge.powerload',
  'recharge.scratchCard',
  'recharge.tbps',
  'product.sell',
  'stock.sim',
  'stock.product',
  'stock.return',
  'stock.reconcile',
  'requisition.create',
  'commission.view',
  'commission.statement',
  'wallet.view',
  'outstanding.view',
  'report.sales',
  'report.transaction',
  'report.target',
  'campaign.view',
  'campaign.own',
  'offer.view',
  'complaint.create',
  'complaint.track',
  'notification.view',
  'support.contact',
]

/** Sales representative — moves stock along a route, does not activate SIMs. */
const SR: Capability[] = [
  'customer.search',
  'stock.sim',
  'stock.product',
  'stock.transfer',
  'stock.return',
  'stock.reconcile',
  'sr.route',
  'sr.allocate',
  'retailer.manage',
  'fieldVisit.log',
  'posm.audit',
  'commission.view',
  'report.sales',
  'report.target',
  'campaign.view',
  'complaint.create',
  'complaint.track',
  'notification.view',
  'support.contact',
]

/** Dealer — raises demand, deposits, receives challan, runs SRs and retailers. */
const DEALER: Capability[] = [
  'customer.search',
  'stock.sim',
  'stock.product',
  'stock.transfer',
  'stock.return',
  'stock.reconcile',
  'requisition.create',
  'requisition.approve',
  'lifting.request',
  'lifting.depositSlip',
  'lifting.challan',
  'sr.route',
  'sr.allocate',
  'retailer.manage',
  'retailer.onboard',
  'user.manage',
  'commission.view',
  'commission.statement',
  'wallet.view',
  'payment.collect',
  'settlement.view',
  'outstanding.view',
  'subsidy.view',
  'report.sales',
  'report.transaction',
  'report.target',
  'report.performance',
  'campaign.view',
  'offer.view',
  'complaint.create',
  'complaint.track',
  'notification.view',
  'support.contact',
]

/** Field officer — recommends demand, verifies the deposit slip, works the market. */
const FIELD_OFFICER: Capability[] = [
  'customer.search',
  'stock.sim',
  'lifting.recommend',
  'lifting.depositVerify',
  'retailer.manage',
  'retailer.onboard',
  'fieldVisit.log',
  'posm.audit',
  'territory.manage',
  'report.sales',
  'report.target',
  'report.performance',
  'campaign.view',
  'complaint.track',
  'notification.view',
  'support.contact',
]

/** Zonal in-charge — approves the quantity, owns the zone. */
const ZONAL: Capability[] = [
  'customer.search',
  'stock.sim',
  'stock.product',
  'inventory.zonal',
  'lifting.approve',
  'requisition.approve',
  'retailer.manage',
  'retailer.onboard',
  'user.manage',
  'territory.manage',
  'fieldVisit.log',
  'posm.audit',
  'geofence.manage',
  'device.monitor',
  'commission.view',
  'outstanding.view',
  'subsidy.view',
  'report.sales',
  'report.transaction',
  'report.target',
  'report.performance',
  'campaign.view',
  'offer.view',
  'complaint.create',
  'complaint.track',
  'notification.view',
  'support.contact',
]

/** Zonal invoice officer — generates the ERP invoice against a verified deposit. */
const INVOICE_OFFICER: Capability[] = [
  'lifting.depositVerify',
  'lifting.invoice',
  'lifting.challan',
  'inventory.zonal',
  'stock.sim',
  'report.transaction',
  'notification.view',
  'support.contact',
]

/** Inventory officer — cross-verifies, releases stock, issues the challan. */
const INVENTORY_OFFICER: Capability[] = [
  'inventory.zonal',
  'inventory.central',
  'stock.sim',
  'stock.product',
  'stock.transfer',
  'stock.return',
  'stock.reconcile',
  'requisition.approve',
  'lifting.challan',
  'report.transaction',
  'notification.view',
  'support.contact',
]

/** F&A revenue assurance — the gate between invoice and stock release. */
const REVENUE_ASSURANCE: Capability[] = [
  'lifting.revenueAssurance',
  'lifting.invoice',
  'settlement.view',
  'outstanding.view',
  'subsidy.view',
  'report.transaction',
  'report.performance',
  'notification.view',
  'support.contact',
]

/** Branch head — oversight across zones, no counter operations. */
const BRANCH_HEAD: Capability[] = [
  'lifting.approve',
  'inventory.zonal',
  'retailer.manage',
  'user.manage',
  'territory.manage',
  'device.monitor',
  'geofence.manage',
  'commission.view',
  'settlement.view',
  'outstanding.view',
  'subsidy.view',
  'report.sales',
  'report.transaction',
  'report.target',
  'report.performance',
  'campaign.view',
  'complaint.track',
  'notification.view',
  'support.contact',
]

/** CSIM — central sales & inventory management. */
const CSIM: Capability[] = [
  'inventory.central',
  'inventory.zonal',
  'stock.sim',
  'stock.product',
  'stock.transfer',
  'stock.return',
  'stock.reconcile',
  'requisition.approve',
  'lifting.challan',
  'sim.choiceNumber',
  'report.sales',
  'report.transaction',
  'report.performance',
  'notification.view',
  'support.contact',
]

/** Every capability in the system. Kept exhaustive by the Record below. */
const ALL: Capability[] = [
  'sim.activate',
  'sim.replace',
  'sim.choiceNumber',
  'sim.ownership',
  'sim.planMigration',
  'customer.search',
  'customer.view360',
  'mnp.portIn',
  'mnp.portOut',
  'mnp.status',
  'recharge.sell',
  'recharge.flexiload',
  'recharge.powerload',
  'recharge.scratchCard',
  'recharge.tbps',
  'product.sell',
  'stock.sim',
  'stock.product',
  'stock.transfer',
  'stock.return',
  'stock.reconcile',
  'requisition.create',
  'requisition.approve',
  'lifting.request',
  'lifting.recommend',
  'lifting.approve',
  'lifting.depositSlip',
  'lifting.depositVerify',
  'lifting.invoice',
  'lifting.revenueAssurance',
  'lifting.challan',
  'inventory.central',
  'inventory.zonal',
  'sr.route',
  'sr.allocate',
  'commission.view',
  'commission.statement',
  'wallet.view',
  'payment.collect',
  'settlement.view',
  'outstanding.view',
  'subsidy.view',
  'report.sales',
  'report.transaction',
  'report.target',
  'report.performance',
  'campaign.view',
  'campaign.own',
  'offer.view',
  'complaint.create',
  'complaint.track',
  'notification.view',
  'support.contact',
  'retailer.manage',
  'retailer.onboard',
  'retailer.provision',
  'user.manage',
  'territory.manage',
  'fieldVisit.log',
  'posm.audit',
  'geofence.manage',
  'device.monitor',
]

export const CAPABILITIES_BY_ROLE: Record<Role, Capability[]> = {
  retailer: RETAILER,
  sr: SR,
  dealer: DEALER,
  // Online dealers sell without a physical outlet: no stock movement.
  onlineDealer: DEALER.filter(
    (c) => !c.startsWith('stock.') && !c.startsWith('sr.') && c !== 'lifting.challan',
  ),
  subDealer: DEALER.filter((c) => c !== 'user.manage' && c !== 'retailer.onboard'),
  fieldOfficer: FIELD_OFFICER,
  zonal: ZONAL,
  invoiceOfficer: INVOICE_OFFICER,
  inventoryOfficer: INVENTORY_OFFICER,
  revenueAssurance: REVENUE_ASSURANCE,
  branchHead: BRANCH_HEAD,
  csim: CSIM,
  admin: ALL,
}
