/**
 * Makes an Expo web export servable by GitHub Pages.
 *
 * Three things Pages needs that `expo export` does not produce, and each one
 * fails in a way that looks like "the app is broken" rather than like a hosting
 * problem:
 *
 *  1. **`.nojekyll`** — Pages runs Jekyll over the branch by default, and
 *     Jekyll silently drops every directory whose name starts with an
 *     underscore. Expo puts the entire bundle in `_expo/`. Without this file
 *     the page loads and the app never boots.
 *  2. **`404.html`** — the app is a single page. Pages has no rewrite rule, so
 *     a reload on any path other than `/` returns its 404. Serving a copy of
 *     `index.html` as the 404 body turns that into a normal deep-link load.
 *  3. **A landing check** — the export is verified to contain what it should
 *     before it is published, because a broken deploy on Pages is public.
 *
 * It also corrects the shell's `lang` attribute, which Expo hard-codes to
 * English.
 *
 * Run: npm run pages  (export first — this only post-processes `dist/`)
 */
import { copyFileSync, existsSync, readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const dist = resolve(here, '../dist')

if (!existsSync(dist)) {
  console.error('pages: dist/ does not exist — run `npm run export:web` first.')
  process.exit(1)
}

const index = join(dist, 'index.html')
if (!existsSync(index)) {
  console.error('pages: dist/index.html is missing — the export did not complete.')
  process.exit(1)
}

if (!existsSync(join(dist, '_expo'))) {
  console.error('pages: dist/_expo is missing — the export produced no bundle.')
  process.exit(1)
}

/**
 * The exported shell is generated by Expo and says `lang="en"`. This app is
 * Bangla-first: the attribute is what a screen reader picks a voice from and
 * what the browser picks a font fallback from, and Bangla rendered through an
 * English fallback is where matras go missing. There is no template to edit
 * for a non-router web export, so it is corrected here.
 */
let html = readFileSync(index, 'utf8')
html = html.replace('<html lang="en">', '<html lang="bn">')
const META = [
  '    <meta name="theme-color" content="#0b7a4f" />',
  // Says what this is, on a public URL: a frontend demo against mocks. Nobody
  // finding it should be able to mistake it for a live retailer system.
  '    <meta name="description" content="Teletalk One — retailer app. Frontend demo running against in-repo mocks. No live customer data." />',
  '  </head>',
].join('\n')

if (!html.includes('name="theme-color"')) {
  html = html.replace('</head>', META)
}
writeFileSync(index, html)

writeFileSync(join(dist, '.nojekyll'), '')
copyFileSync(index, join(dist, '404.html'))

const top = readdirSync(dist)
console.log(`pages: dist/ ready — ${top.length} entries, .nojekyll and 404.html written.`)
